name: "Unit Test"

on:
  push:
    branches:
      - 'feature/**'

env:
  TF_VERSION: "1.3.0"
  GO_VERSION: "1.19"
  AWS_DEFAULT_REGION: "ap-northeast-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  terraform:
    name: "Unit Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download Go Modules
        run: go mod tidy
        working-directory: ./test

      - name: Run Go Test
        run: go test -v -tags=unit
        working-directory: ./test